# Generated by Django 2.0 on 2018-10-02 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(blank=True, max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('mail', models.EmailField(blank=True, max_length=30)),
                ('message', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'db_table': 'resume',
            },
        ),
    ]
